
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: php
  name: php-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts: 
      - php.external.com
    secretName: tls-secret
  rules:
  - host: php.external.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: php-svc
              port:
                number: 8080
