apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: php
  newName: ericsonmessias/php
  newTag: 56e0599762246b6d331cdc16cc58ca9dfbb6a985
