apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: php
  newName: ericsonmessias/php
  newTag: eee329687372aa4d0eb5f3ae954a376f154497ec
